//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeatingSystemAdministration
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int Id { get; set; }
        public double kWh { get; set; }
        public double CubeMeters { get; set; }
        public double UsageHours { get; set; }
        public System.DateTime Year { get; set; }
    
        public virtual Meter Meter { get; set; }

        public override string ToString()
        {
            return this.kWh + "kWh " + this.CubeMeters + "m^3 " + UsageHours + "hours for year: " + Year.Year;
        }
    }
}
